# config.py

DATA_FOLDER = "dax_pattern_trading/data"

SL_PERCENTAGE = 0.04  
TP_PERCENTAGE = 0.02  
POSITION_SIZE = 0.1   

CHART_WIDTH = 1200
CHART_HEIGHT = 800
CHART_BG_COLOR = "black"
CHART_PAPER_COLOR = "black"
CHART_FONT_COLOR = "white"
